name: Build website

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Use GitHub-hosted runner, NOT self-hosted
    container:
      image: ubuntu:22.04  # ✅ Force Ubuntu 22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Manually Install Ruby (Backup Plan)
        run: |
          sudo apt update
          sudo apt install -y ruby-full
          ruby -v

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
