name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Ensure using GitHub-hosted runner
    container:
      image: ubuntu:22.04  # ✅ Force Ubuntu 22.04

    steps:
      - name: Debug Runner Information
        run: |
          echo "Runner OS Information:"
          uname -a
          echo "GitHub Runner Name: $RUNNER_NAME"
          echo "GitHub Runner OS: $RUNNER_OS"
          echo "GitHub Runner Arch: $RUNNER_ARCH"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Manually Install Ruby
        run: |
          sudo apt update
          sudo apt install -y ruby-full
          ruby -v

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04  # ✅ Ensure using GitHub-hosted runner
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
